Models/Customer.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;
namespace massage.Models
{
    public class Customer
    {
        [Key]
        public int CustomerId { get; set; }

        [Required]
        [Display(Name = "First Name")]
        [MinLength(2)]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        [MinLength(2)]
        public string LastName { get; set; }

        [Required]
        [Display(Name = "Address Line 1")]
        public string Address1 { get; set; }

        [Display(Name = "Address Line 2")]
        public string Address2 { get; set; }

        [Required]
        public string City { get; set; }

        [Required]
        public string State { get; set; }

        [Required]
        [Range(1,99999)]
        [Display(Name = "Zip Code")]
        public int Zip { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Phone Number (123-456-7890)")]
        public string Phone { get; set; }

        public string Notes { get; set; }

        public List<Reservation> Reservations { get; set; }

        //removed foreign key InsuranceID
        public int InsuranceId { get; set; }
        public Insurance Insurance { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public DateTime UpdatedAt { get; set; } = DateTime.Now;   
    }
}

Models/Insurance.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;
namespace massage.Models
{
    public class Insurance
    {
        [Key]
        public int InsuranceId { get; set; }

        [Required]
        [MinLength(2)]
        public string Name { get; set; }

        public List<PInsurance> Practitioners { get; set; }

        public List<Customer> Customers { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public DateTime UpdatedAt { get; set; } = DateTime.Now;
    }
}

Models/Reservation.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;
namespace massage.Models
{
    public class Reservation
    {
        [Key]
        public int ReservationId { get; set; }

        public string Notes { get; set; }

        public int CustomerId { get; set; }
        public Customer Customer { get; set; }

        public int PractitionerId { get; set; }
        public User Practitioner { get; set; }

        public int CreatorId { get; set; }
        public User Creator { get; set; }

        public int ServiceId { get; set; }
        public Service Service { get; set; }

        public int RoomId { get; set; }
        public Room Room { get; set; }

        public int TimeslotId { get; set; }
        public Timeslot Timeslot { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public DateTime UpdatedAt { get; set; } = DateTime.Now;
    }
}

Controllers/ReceptionistController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using massage.Models;
using Microsoft.AspNetCore.Http;

namespace massage.Controllers
{
    [Route("rec")]
    public class ReceptionistController : Controller
    {
        // Database setup
        public ProjectContext dbContext;
        public ReceptionistController(ProjectContext context)
        {
            dbContext = context;
        }

        // User session to keep track who is logged in!!
        private User UserSession {
            get {return dbContext.Users.FirstOrDefault(u => u.UserId == HttpContext.Session.GetInt32("UserId"));}
            set {HttpContext.Session.SetInt32("UserId", value.UserId);}
        }
        // Redirects non-practitioner users to their respective dashboards
        // see PractitionerController.AccessCheck for details
        private string[] AccessCheck() {
            User ActiveUser = UserSession;
            if(ActiveUser == null) return new string[]{"Login", "Login"};
            else if (ActiveUser.Role == 0) return new string[]{"Dashboard", "Home"};
            else if (ActiveUser.Role == 1) return new string[]{"Dashboard", "Practitioner"};
            return null;
        }

        // ROUTES

        // REC DASHBOARD
        // Access from Receptionst: "dashboard"
        // Access from anywhere else: "/rec/dashboard"
        [HttpGet("dashboard")]
        public IActionResult Dashboard()
        {
            // Checks User's role and login
            string[] check = AccessCheck();
            if(check != null) return RedirectToAction(check[0], check[1]);
            Generate.CheckTimeslots(dbContext); // check if timeslots need to be generated
            ViewModel vm = new ViewModel();
            vm.CurrentUser = UserSession;
            vm.AllUsers = Query.AllUsers(dbContext);
            vm.AllCustomers = Query.AllCustomers(dbContext);
            vm.AllInsurances = Query.AllInsurances(dbContext);
            vm.AllServices = Query.AllServices(dbContext);
            vm.AllTimeslots = Query.AllTimeslots(dbContext);
            vm.AllPractitioners = Query.AllPractitioners(dbContext);
            vm.AllReservations = Query.AllReservations(dbContext);
            return PartialView("RDashboard",vm);
        }
        [HttpGet("insurances")]
        public IActionResult Insurances() {
            string[] check = AccessCheck();
            if(check != null) return RedirectToAction(check[0], check[1]);
            ViewModel vm = new ViewModel();
            vm.CurrentUser = UserSession;
            vm.AllInsurances = Query.AllInsurances(dbContext);
            vm.AllUsers = Query.AllUsers(dbContext);
            return PartialView(vm);
        }

        [HttpGet("CurrentReservation/{id}")]
        public IActionResult CurrentReservation(int id)
        {
            string[] check = AccessCheck();
            if(check != null) return RedirectToAction(check[0], check[1]);
            ViewModel vm = new ViewModel();
            vm.CurrentUser = Query.OneReceptionist(UserSession.UserId, dbContext);
            vm.AllUsers = Query.AllUsers(dbContext);
            vm.AllCustomers = Query.AllCustomers(dbContext);
            vm.AllInsurances = Query.AllInsurances(dbContext);
            vm.AllServices = Query.AllServices(dbContext);
            vm.AllTimeslots = Query.AllTimeslots(dbContext);
            vm.AllPractitioners = Query.AllPractitioners(dbContext);
            vm.AllReservations = Query.AllReservations(dbContext);
            vm.OneReservation = Query.OneReservation(id, dbContext);
            return PartialView(vm);
        }

        // ALL RESERVATIONS
        [HttpGet("all_res")]
        public IActionResult AllReservations()
        {
            // Checks User's role and login
            string[] check = AccessCheck();
            if(check != null) return RedirectToAction(check[0], check[1]);
            Query.AllReservations(dbContext);
            return PartialView();
        }

        // FORM PAGE??
        [HttpGet("NewReservation")]
        public IActionResult NewReservation()
        {
            // Checks User's role and login
            string[] check = AccessCheck();
            if(check != null) return RedirectToAction(check[0], check[1]);
            Generate.CheckTimeslots(dbContext); // check if timeslots need to be generated
            ViewModel vm = new ViewModel();
            vm.CurrentUser = Query.OneReceptionist(UserSession.UserId, dbContext);
            vm.AllUsers = Query.AllUsers(dbContext);
            vm.AllCustomers = Query.AllCustomers(dbContext);
            vm.AllInsurances = Query.AllInsurances(dbContext);
            vm.AllServices = Query.AllServices(dbContext);
            vm.AllTimeslots = Query.AllTimeslots(dbContext);
            vm.AllPractitioners = Query.AllPractitioners(dbContext);
            vm.OneReservation = new Reservation();
            vm.OneReservation.CreatorId = vm.CurrentUser.UserId;
            return PartialView(vm);
        }
        [HttpGet("newinsurance")]
        public IActionResult NewInsurance()
        {
            string[] check = AccessCheck();
            if(check != null) return RedirectToAction(check[0], check[1]);
            return View();
        }
        [HttpPost("CreateInsurance")]
        public IActionResult CreateInsurance(Insurance newInsurance)
        {
            User currentUser = dbContext.Users.Where(u => u.UserId == HttpContext.Session.GetInt32("UserId")).SingleOrDefault();
            if (ModelState.IsValid)
            {
                dbContext.Add(newInsurance);
                dbContext.SaveChanges();
                return RedirectToAction("Dashboard");
            }
            else
            {
                return PartialView("NewInsurance");
            }
        }
        [HttpGet("Customers")]
        public IActionResult Customers() {
            string[] check = AccessCheck();
            if(check != null) return RedirectToAction(check[0], check[1]);
            ViewModel vm = new ViewModel();
            vm.CurrentUser = UserSession;
            vm.AllCustomers = Query.AllCustomers(dbContext);
            vm.AllUsers = Query.AllUsers(dbContext);
            return PartialView(vm);
        }

        // Create Reservation from timeslot id
        [HttpPost("CreateReservation")]
        public IActionResult CreateReservation(ViewModel vm)
        {
            string[] check = AccessCheck();
            if(check != null) return RedirectToAction(check[0], check[1]);
            if (vm.OneReservation.CreatorId == 0 || vm.OneReservation.CustomerId == 0 || vm.OneReservation.PractitionerId == 0 || vm.OneReservation.ServiceId == 0 || vm.OneReservation.TimeslotId == 0)
            {
                ViewBag.errormsg = "You must select all options!";
                vm.CurrentUser = Query.OneReceptionist(UserSession.UserId, dbContext);
                vm.AllUsers = Query.AllUsers(dbContext);
                vm.AllCustomers = Query.AllCustomers(dbContext);
                vm.AllInsurances = Query.AllInsurances(dbContext);
                vm.AllServices = Query.AllServices(dbContext);
                vm.AllTimeslots = Query.AllTimeslots(dbContext);
                vm.AllPractitioners = Query.AllPractitioners(dbContext);
                vm.OneReservation.Practitioner = Query.OnePractitioner(vm.OneReservation.PractitionerId, dbContext);
                return PartialView("NewReservation", vm);
            }
            Timeslot thisTS = Query.OneTimeslot(vm.OneReservation.TimeslotId, dbContext);
            vm.OneTimeslot = thisTS;
            vm.AllPractitioners = Query.AllPractitioners(dbContext);
            vm.OneCustomer = Query.OneCustomer(vm.OneReservation.CustomerId, dbContext);
            vm.OneService = Query.OneService(vm.OneReservation.ServiceId, dbContext);
            vm.OneInsurance = Query.OneInsurance(vm.OneCustomer.InsuranceId, dbContext);
            vm.OneReservation.Practitioner = Query.OnePractitioner(vm.OneReservation.PractitionerId, dbContext);
            vm.CurrentUser = UserSession;
            return PartialView("ReservationForm", vm);
        }
        [HttpPost("SubmitReservation")]
        public IActionResult SubmitReservation(ViewModel vm)
        {
            string[] check = AccessCheck();
            if(check != null) return RedirectToAction(check[0], check[1]);
            vm.OneReservation.CreatorId = UserSession.UserId;
            int roomID = 1;
            Timeslot thisTS = Query.OneTimeslot(vm.OneReservation.TimeslotId, dbContext);
            List<int> roomIDList = new List<int>();
            foreach (Reservation resv in thisTS.Reservations)
            {
                roomIDList.Add(resv.RoomId);
            }
            while (roomIDList.IndexOf(roomID) != -1)
            {
                roomID ++;
            }
            vm.OneReservation.RoomId = roomID;
            if (ModelState.IsValid)
            {
                
                // manual validations
                if (vm.OneReservation.CreatorId == 0 || vm.OneReservation.CustomerId == 0 || vm.OneReservation.PractitionerId == 0 || vm.OneReservation.RoomId == 0 || vm.OneReservation.ServiceId == 0 || vm.OneReservation.TimeslotId == 0)
                {
                    ViewBag.errormsg = "An association value was 0, an error has occured";
                    vm.CurrentUser = UserSession;
                    return RedirectToAction("NewReservation");
                }
                Query.CreateReservation(vm.OneReservation, dbContext);
                return RedirectToAction("Dashboard");
            }
            else {
                vm.CurrentUser = UserSession;
                return RedirectToAction("NewReservation");
            }
        }

        // SUBMIT: cancel res
        [HttpPost("CancelReservation/{id}")]

Views/Receptionist/CurrentReservation.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>New Reservation</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css">

  <!-- fullCalendar -->
  <link rel="stylesheet" href="~/plugins/fullcalendar/main.min.css">
  <link rel="stylesheet" href="~/plugins/fullcalendar-daygrid/main.min.css">
  <link rel="stylesheet" href="~/plugins/fullcalendar-timegrid/main.min.css">
  <link rel="stylesheet" href="~/plugins/fullcalendar-bootstrap/main.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
@model ViewModel
<body class="hold-transition sidebar-mini">
<aside class="wrapper">
  <!-- Navbar -->
  <partial name="_NavPartial">

  @{
    ViewModel vm = Model;
  }
  <partial name="_RSidebarPartial" model="vm"/>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
        <div class="card card-info">
          <div class="card-header">
            <h3 class="card-title">
            @{
                DateTime startT = DateTime.Today.AddHours(@Model.OneReservation.Timeslot.Hour);
                DateTime endT = startT.AddHours(1);
            }
                @Model.OneReservation.Timeslot.Date.ToString("MM/dd") from @String.Format("{0:htt}", startT) - @String.Format("{0:htt}", endT)</h3>
                </p>
          </div>
       <div class="container-fluid">
        <div class="row mb-2">
            <div class="card-body">
                <h5 class="card-title">@Model.OneReservation.Customer.FirstName @Model.OneReservation.Customer.LastName</h5>
                <p class="card-text"><small>Notes: @Model.OneReservation.Notes</small></p>
                <p class="card-text"><span style="font-weight:bold">@Model.OneReservation.Service.Name </span> with <span style="font-weight:bold">@Model.OneReservation.Practitioner.FirstName @Model.OneReservation.Practitioner.LastName</span> in Room <span style="font-weight:bold">@Model.OneReservation.Room.RoomId</span></p>
                @if(Model.OneReservation.Notes != null ){
                
                }

            </div> 
        </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
    </div>
    <strong>Copyright &copy; 2020 <a href="h">massage.com</a>.</strong> All rights reserved.
  </footer>
</aside>
<!-- ./wrapper -->

<script src="~/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js?v=1"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>

<!-- jQuery UI -->
<script src="~/plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- AdminLTE App -->
<script src="~/dist/js/adminlte.min.js"></script>
<!-- fullCalendar 2.2.5 -->
<script src="~/plugins/moment/moment.min.js"></script>
<script src="~/plugins/fullcalendar/main.min.js"></script>
<script src="~/plugins/fullcalendar-daygrid/main.min.js"></script>
<script src="~/plugins/fullcalendar-timegrid/main.min.js"></script>
<script src="~/plugins/fullcalendar-interaction/main.min.js"></script>
<script src="~/plugins/fullcalendar-bootstrap/main.min.js"></script>

<!--Practiontioner Scheduler -->
<script src="~/js/timeslotCalendar.js?v=3"></script>

</body>
</html>

Views/Receptionist/DayViewTimeslots.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
@model ViewModel
<body>
    <h2>Timeslots for @Model.AllTimeslots[0].Date</h2>
    @if(Model.AllTimeslots.Count <= 0){
        <p>No Timeslots to Display</p>
    }else{
        @foreach(Timeslot timeslot in Model.AllTimeslots){
            if(timeslot.Hour == 6){
            <p style="color:green;">@timeslot.Hour</p>
            }else if(timeslot.Hour == 7) {
                <p style="color:green;">@timeslot.Hour</p>
            }else if(timeslot.Hour == 8) {
                <p style="color:green;">@timeslot.Hour</p>
            }else{
                <p style="color:red;">@timeslot.Hour</p>
            }
        }
    }
</body>
</html>

Views/Receptionist/NewInsurance.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @{ViewData["Title"] = "New Insurance";}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <Title>Document</Title>
</head>
<body>
    <div class="container">
        <div class="container">
    <div class="row mt-2">
        <h1>Create Insurance</h1>
    </div>
     <div class="row mt-2">
         @model Insurance
        <form asp-action="CreateInsurance" method="post">
            <div class="form-group row">
                <div class="col-sm-5">
                    <span asp-validation-for="Name"></span>
                    <label asp-for="Name"></label>
                </div>
                <div class="col-sm-7">
                    <input type="text" class="form-control border border-dark" asp-for="Name">
                </div>
            </div>
            <div class="form-group row text-right">
                <div class="col-sm-12">
                    <button type="submit" class="btn btn-primary">Create Insurance</button>
                </div>
            </div>
        </form>
    </div>
</div>
    </div>
    
</body>
</html>

Views/Receptionist/NewReservation.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>New Reservation</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css">

  <!-- fullCalendar -->
  <link rel="stylesheet" href="~/plugins/fullcalendar/main.min.css">
  <link rel="stylesheet" href="~/plugins/fullcalendar-daygrid/main.min.css">
  <link rel="stylesheet" href="~/plugins/fullcalendar-timegrid/main.min.css">
  <link rel="stylesheet" href="~/plugins/fullcalendar-bootstrap/main.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
@model ViewModel
<body class="hold-transition sidebar-mini">
<aside class="wrapper">
  <!-- Navbar -->
  <partial name="_NavPartial">

  @{
    ViewModel vm = Model;
  }
  <partial name="_RSidebarPartial" model="vm"/>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
        <div class="card card-info">
          <div class="card-header">
            <h3 class="card-title">Select Date and Time of appointment</h3>
          </div>
       <div class="container-fluid">
        <div class="row mb-2">
      
          <form class="form" asp-action="CreateReservation" asp-controller="Receptionist" method="post">
            <input type="hidden" asp-for="@Model.OneReservation.CreatorId" value="@Model.CurrentUser.UserId">
            <div class="card-body">
              <div class="row">
                <div class="col">
                  <label for="service">Customer:</label>
                  <div class="col mb-2">
                      <select id="custSelector" class="form-control select" asp-for="@Model.OneReservation.CustomerId">
                        <option value="0">Select a Customer</option>
                        @foreach (var cust in Model.AllCustomers)
                        {
                          <option value="@cust.CustomerId">@cust.FirstName @cust.LastName</option>
                        }
                      </select>            
                  </div>
                </div>
                <div class="col">
                  <label for="service">Service:</label>
                  <div class="col mb-2">
                      <select id="servSelector" class="form-control select" asp-for="@Model.OneReservation.ServiceId">
                        <option value="0">Select a Service</option>
                        @foreach (var service in Model.AllServices)
                        {
                          <option value="@service.ServiceId">@service.Name</option>
                        }
                      </select>            
                  </div>
                </div>
                <div class="col">
                  <label for="service">Practiontioner:</label>
                  <div class="col mb-2">
                      <select id="practSelector" class="form-control select" asp-for="@Model.OneReservation.PractitionerId">
                        <option value="0">Select a Practitioner</option>
                        @foreach (var prac in Model.AllPractitioners)
                        {
                          <option value="@prac.UserId">@prac.FirstName @prac.LastName</option>
                        }
                      </select>            
                  </div>
                </div>
                <input type="hidden" value="0" asp-for="@Model.OneReservation.TimeslotId" id="tsid">
              </div>
              <div class="row text-danger small">@ViewBag.errormsg</div>
            </div>
              <div class="form-row mb-2">
              <div id="calendar"></div>
          </div>
            <div class="card-footer">
              <button submit" class="btn btn-info float-right">Next</button>
            </div>
          </form>

        </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
    </div>
    <strong>Copyright &copy; 2020 <a href="h">massage.com</a>.</strong> All rights reserved.
  </footer>
</aside>
<!-- ./wrapper -->

<script src="~/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js?v=1"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>

<!-- jQuery UI -->
<script src="~/plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- AdminLTE App -->
<script src="~/dist/js/adminlte.min.js"></script>
<!-- fullCalendar 2.2.5 -->
<script src="~/plugins/moment/moment.min.js"></script>
<script src="~/plugins/fullcalendar/main.min.js"></script>
<script src="~/plugins/fullcalendar-daygrid/main.min.js"></script>
<script src="~/plugins/fullcalendar-timegrid/main.min.js"></script>
<script src="~/plugins/fullcalendar-interaction/main.min.js"></script>
<script src="~/plugins/fullcalendar-bootstrap/main.min.js"></script>

<!--Practiontioner Scheduler -->
<script src="~/js/timeslotCalendar.js?v=3"></script>

</body>
</html>

Views/Receptionist/ReservationForm.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>New Reservation</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css">

  <!-- fullCalendar -->
  <link rel="stylesheet" href="~/plugins/fullcalendar/main.min.css">
  <link rel="stylesheet" href="~/plugins/fullcalendar-daygrid/main.min.css">
  <link rel="stylesheet" href="~/plugins/fullcalendar-timegrid/main.min.css">
  <link rel="stylesheet" href="~/plugins/fullcalendar-bootstrap/main.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
@model ViewModel
<body class="hold-transition sidebar-mini">
<aside class="wrapper">
  <!-- Navbar -->
  <partial name="_NavPartial">

  @{
    ViewModel vm = Model;
  }
  <partial name="_RSidebarPartial" model="vm"/>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">

    <!-- Main content -->
    <section class="content">
        <div class="card card-info">
          <div class="card-header">
            <h3 class="card-title">Confirm appointment</h3>
          </div>
       <div class="container-fluid">
        <div class="row mb-2">
          <form class="form" asp-action="SubmitReservation" asp-controller="Receptionist" method="post">
            <input type="hidden" value="@Model.OneReservation.TimeslotId" asp-for="@Model.OneReservation.TimeslotId" id="tsid">
            <input type="hidden" value="@Model.OneReservation.ServiceId" asp-for="@Model.OneReservation.ServiceId">
            <input type="hidden" value="@Model.OneReservation.PractitionerId" asp-for="@Model.OneReservation.PractitionerId">
            <input type="hidden" value="@Model.OneReservation.CustomerId" asp-for="@Model.OneReservation.CustomerId">
            <div class="card-body">
              <div class="row">
                <div class="col">
                  <label for="service">Customer Name: @Model.OneCustomer.FirstName @Model.OneCustomer.LastName</label>
                </div>
                <div class="col">
                  <label for="service">Selected Service: @Model.OneService.Name</label>
                </div>
                <div class="col">
                  <label for="service">Selected Practiontioner: @Model.OneReservation.Practitioner.FirstName @Model.OneReservation.Practitioner.LastName</label>
                </div>
              </div>
              <textarea asp-for="@Model.OneReservation.Notes"></textarea>
            </div>
              <div class="form-row mb-2">
              <div id="calendar"></div>
          </div>
            <div class="card-footer">
              <button type="submit" class="btn btn-info float-right">Submit</button>
            </div>
          </form>

        </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
    </div>
    <strong>Copyright &copy; 2020 <a href="h">massage.com</a>.</strong> All rights reserved.
  </footer>
</aside>
<!-- ./wrapper -->

<script src="~/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>

<!-- jQuery UI -->
<script src="~/plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- AdminLTE App -->
<script src="~/dist/js/adminlte.min.js"></script>
<!-- fullCalendar 2.2.5 -->
<script src="~/plugins/moment/moment.min.js"></script>
<script src="~/plugins/fullcalendar/main.min.js"></script>
<script src="~/plugins/fullcalendar-daygrid/main.min.js"></script>
<script src="~/plugins/fullcalendar-timegrid/main.min.js"></script>
<script src="~/plugins/fullcalendar-interaction/main.min.js"></script>
<script src="~/plugins/fullcalendar-bootstrap/main.min.js"></script>

<!--Practiontioner Scheduler -->
<script src="~/js/timeslotCalendar.js"></script>

</body>
</html>